"""
Validates Cypher generated by the LLM before execution.

This validator prevents hallucinated labels,
relationships, properties, and dangerous queries.
"""

import re
from pathlib import Path

GRAPH_SCHEMA_FILE = "graph_schema.md"

class CypherValidator:

    ####################################################################
    # Initialization
    ####################################################################

    def __init__(self, schema_file=GRAPH_SCHEMA_FILE):

        self.schema = Path(schema_file).read_text(
            encoding="utf-8"
        )

        self.labels = self._extract_labels()
        self.relationships = self._extract_relationships()
        self.properties = self._extract_properties()

    ####################################################################
    # Public API
    ####################################################################

    def validate(self, cypher: str):

        self.validate_not_empty(cypher)

        self.validate_single_statement(cypher)

        self.validate_read_only(cypher)

        self.validate_labels(cypher)

        self.validate_relationships(cypher)

        self.validate_properties(cypher)

        return True

    ####################################################################
    # Rule 1
    ####################################################################

    @staticmethod
    def validate_not_empty(cypher):

        if not cypher.strip():

            raise ValueError("Generated Cypher is empty.")

    ####################################################################
    # Rule 2
    ####################################################################

    @staticmethod
    def validate_single_statement(cypher):

        if ";" in cypher.strip().rstrip(";"):

            raise ValueError(
                "Multiple Cypher statements detected."
            )

    ####################################################################
    # Rule 3
    ####################################################################

    @staticmethod
    def validate_read_only(cypher):

        forbidden = [
            "CREATE",
            "MERGE",
            "DELETE",
            "DETACH",
            "REMOVE",
            "SET",
            "DROP",
            "CALL dbms",
            "CALL apoc",
            "LOAD CSV",
        ]

        upper = cypher.upper()

        for keyword in forbidden:

            if keyword in upper:

                raise ValueError(
                    f"Forbidden keyword detected: {keyword}"
                )

    ####################################################################
    # Rule 4
    ####################################################################

    def validate_labels(self, cypher):

        labels = re.findall(
            r":([A-Za-z_][A-Za-z0-9_]*)",
            cypher,
        )

        labels = [
            l for l in labels
            if l in self.labels or l not in self.relationships
        ]

        for label in labels:

            if label not in self.labels:

                raise ValueError(
                    f"Unknown label: {label}"
                )

    ####################################################################
    # Rule 5
    ####################################################################

    def validate_relationships(self, cypher):

        rels = re.findall(
            r"\[:([A-Z_]+)",
            cypher,
        )

        for rel in rels:

            if rel not in self.relationships:

                raise ValueError(
                    f"Unknown relationship: {rel}"
                )

    ####################################################################
    # Rule 6
    ####################################################################

    def validate_properties(self, cypher):

        props = re.findall(
            r"\.\s*([A-Za-z_][A-Za-z0-9_]*)",
            cypher,
        )

        for prop in props:

            if prop not in self.properties:

                raise ValueError(
                    f"Unknown property: {prop}"
                )

    ####################################################################
    # Schema Parsing
    ####################################################################

    def _extract_labels(self):

        labels = []

        for line in self.schema.splitlines():

            line = line.strip()

            if (
                line
                and not line.startswith("=")
                and not line.startswith("#")
                and "Properties" not in line
                and "Examples" not in line
                and not line.startswith("-")
                and "(" not in line
                and line
                not in (
                    "NODE LABELS",
                    "RELATIONSHIPS",
                )
            ):

                if line[0].isupper():

                    labels.append(line)

        return set(labels)

    ####################################################################

    def _extract_relationships(self):

        rels = re.findall(
            r"\[:([A-Z_]+)\]",
            self.schema,
        )

        return set(rels)

    ####################################################################

    def _extract_properties(self):

        props = re.findall(
            r"• ([A-Za-z_][A-Za-z0-9_]*)",
            self.schema,
        )

        return set(props)
    
    
if __name__ == "__main__":
    validator = CypherValidator()

    # cypher = """
    #     MATCH (p:Person)-[:MANAGES]->(b:Person)
    #     WHERE b.name = "Bob"
    #     RETURN p.name
    # """
    
    cypher = """
        MATCH (p:Employee)
        RETURN p
    """ # should raise an error because Employee is not a valid label
    
    try:
        validator.validate(cypher)
        print("Cypher is valid.")
    except ValueError as e:
        print(f"Validation error: {e}")