"""
agents/analytics_agent.py
----------------------------
AGENT 2: ANALYTICS AGENT

Job: turn raw campaign rows into KPIs (CTR, CPC, CPA, ROAS), and produce
short analyst notes flagging anything anomalous or notable.

DESIGN NOTE -- why compute_kpis is NOT an LLM-callable tool:
This is the most important design decision in the whole project, and
worth discussing explicitly with students. `compute_kpis` needs every
raw campaign row as input. If it were an LLM tool, the model would have
to reproduce all of that data (potentially thousands of rows) inside
its own tool-call arguments -- slow, expensive, and a real risk of the
model silently corrupting numbers it doesn't need to touch. Numeric
aggregation is exactly the kind of task you want done by tested,
deterministic code, not regenerated by a language model.

So: `compute_kpis` is called directly, in Python, by `run()`. The LLM
only ever sees the *already-computed, compact* KPI summary (a handful
of numbers per channel) -- small enough to reason over safely -- plus
one genuinely LLM-appropriate tool: `lookup_channel_context`, a small
qualitative-knowledge lookup the model can choose to call per channel
before writing its notes.
"""

from collections import defaultdict

from agents.base_agent import BaseAgent
from agents.tool_schemas import LookupChannelContextInput
from logging_config import get_logger


class AnalyticsAgent(BaseAgent):

    SYSTEM_PROMPT = (
        "You are a marketing analytics agent. You will be given already-computed "
        "KPIs (CTR, CPC, CPA, ROAS) per channel, compared against industry "
        "benchmarks. Your job is to write 2-4 sentences flagging anything "
        "anomalous, concerning, or notably good -- the way a sharp human analyst "
        "would when handing this off to a manager. You may call "
        "lookup_channel_context on any channel if extra qualitative context would "
        "make your notes sharper (e.g. known seasonality or audience quirks)."
    )

    # Stands in for a lightweight internal knowledge base / retrieval call.
    _CHANNEL_KNOWLEDGE = {
        "Google Search": "High-intent traffic; typically the most efficient channel for direct-response conversions.",
        "Facebook":      "Broad reach but often used for awareness; conversion efficiency tends to lag Search.",
        "Instagram":     "Skews younger and more visual; performance is seasonal and campaign-creative dependent.",
    }

    def __init__(self, use_llm=None):
        super().__init__(name="AnalyticsAgent", use_llm=use_llm)
        self.register_tool(
            name="lookup_channel_context",
            func=self._lookup_channel_context,
            description="Looks up qualitative context about a marketing channel (audience, seasonality, typical role in the funnel) to help interpret its KPIs.",
            input_model=LookupChannelContextInput,
        )

    # ---- deterministic math (never delegated to the LLM) ----
    def compute_kpis(self, rows: list[dict], benchmarks: dict) -> dict:
        totals = defaultdict(lambda: {
            "impressions": 0, "clicks": 0, "spend": 0.0,
            "conversions": 0, "revenue": 0.0,
        })
        for r in rows:
            t = totals[r["channel"]]
            t["impressions"] += r["impressions"]
            t["clicks"] += r["clicks"]
            t["spend"] += r["spend"]
            t["conversions"] += r["conversions"]
            t["revenue"] += r["revenue"]

        report = {}
        for channel, t in totals.items():
            ctr = t["clicks"] / t["impressions"] if t["impressions"] else 0
            cpc = t["spend"] / t["clicks"] if t["clicks"] else 0
            cpa = t["spend"] / t["conversions"] if t["conversions"] else 0
            roas = t["revenue"] / t["spend"] if t["spend"] else 0
            bench = benchmarks.get(channel, {})
            report[channel] = {
                "ctr": round(ctr, 4), "cpc": round(cpc, 2),
                "cpa": round(cpa, 2), "roas": round(roas, 2),
                "spend": round(t["spend"], 2), "revenue": round(t["revenue"], 2),
                "benchmark_ctr": bench.get("ctr"),
                "benchmark_cpa": bench.get("cpa"),
                "benchmark_roas": bench.get("roas"),
            }
        return report

    # ---- tool implementation (the one thing the LLM actually calls) ----
    def _lookup_channel_context(self, channel: str) -> str:
        return self._CHANNEL_KNOWLEDGE.get(channel, "No additional context available for this channel.")

    # ---- deterministic fallback path (no LLM/tool-calling) ----
    def _fallback_run(self, kpis: dict) -> str:
        log = get_logger(self.name)
        log.info("running in rule-based mode (no LLM)")
        flags = []
        for channel, kpi in kpis.items():
            if kpi["roas"] < 1:
                flags.append(f"{channel} is losing money (ROAS {kpi['roas']} < 1.0)")
            elif kpi["benchmark_ctr"] and kpi["ctr"] < kpi["benchmark_ctr"] * 0.7:
                flags.append(f"{channel} CTR ({kpi['ctr']:.2%}) is well below benchmark")
        return "[Rule-based mode] " + ("; ".join(flags) if flags else "No channels breached rule-based thresholds.")

    # ---- entry point ----
    def run(self, data_agent_output: dict) -> dict:
        self.log.info("starting run")
        rows = data_agent_output["campaign_data"]
        benchmarks = data_agent_output["benchmarks"]

        kpis = self.compute_kpis(rows, benchmarks)
        self.remember({"type": "kpis_computed", "kpis": kpis})
        self.log.info("computed KPIs", extra={"channel_count": len(kpis)})

        if self._client is None:
            notes = self._fallback_run(kpis)
        else:
            notes = self.run_agentic_loop(
                system_prompt=self.SYSTEM_PROMPT,
                user_message=f"Here are this period's computed KPIs per channel:\n{kpis}",
            )

        self.remember({"type": "analysis_notes", "notes": notes})
        return {"kpis": kpis, "benchmarks": benchmarks, "notes": notes}
