"""
reports/pdf_report.py
PDF Generator — builds a styled A4 PDF with:
  • Header banner
  • Question & SQL
  • AI data summary
  • Chart image
  • Full narrative report
  • Data table (up to 30 rows)
  • Footer
"""

import io
from datetime import datetime

import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    Image, HRFlowable, KeepTogether,
)

# ── Palette ────────────────────────────────────────────────────────────────────
DARK      = colors.HexColor("#1a1f2e")
BLUE      = colors.HexColor("#4f8ef7")
LIGHT_BG  = colors.HexColor("#f4f6fb")
MID_GREY  = colors.HexColor("#dde2ef")
WHITE     = colors.white
TEXT_DARK = colors.HexColor("#2c3e50")


def _fig_to_image(fig) -> Image | None:
    if fig is None:
        return None
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=150, bbox_inches="tight",
                facecolor=fig.get_facecolor())
    buf.seek(0)
    return Image(buf, width=17 * cm, height=8.5 * cm)


def _table_flowable(df: pd.DataFrame, max_rows: int = 30):
    df_show   = df.head(max_rows).astype(str)
    header    = list(df_show.columns)
    data_rows = df_show.values.tolist()
    all_rows  = [header] + data_rows

    n_cols    = len(header)
    col_w     = (17 * cm) / n_cols

    tbl = Table(all_rows, colWidths=[col_w] * n_cols, repeatRows=1)
    tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0),  DARK),
        ("TEXTCOLOR",     (0, 0), (-1, 0),  WHITE),
        ("FONTNAME",      (0, 0), (-1, 0),  "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, 0),  8.5),
        ("ALIGN",         (0, 0), (-1, 0),  "CENTER"),
        ("BOTTOMPADDING", (0, 0), (-1, 0),  6),
        ("TOPPADDING",    (0, 0), (-1, 0),  6),
        ("FONTSIZE",      (0, 1), (-1, -1), 7.5),
        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [WHITE, LIGHT_BG]),
        ("GRID",          (0, 0), (-1, -1), 0.4, MID_GREY),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",    (0, 1), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 3),
    ]))
    return tbl


def generate_pdf(
    question:  str,
    sql:       str,
    df:        pd.DataFrame,
    summary:   str,
    narrative: str,
    fig=None,
) -> bytes:

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=2*cm, rightMargin=2*cm,
        topMargin=2*cm,  bottomMargin=2*cm,
    )
    base = getSampleStyleSheet()

    # ── Styles ─────────────────────────────────────────────────────────────────
    S = {
        "title": ParagraphStyle("T", parent=base["Normal"],
            fontSize=22, textColor=WHITE, backColor=DARK,
            alignment=TA_CENTER, spaceAfter=2, spaceBefore=2,
            borderPad=14, fontName="Helvetica-Bold"),

        "subtitle": ParagraphStyle("Sub", parent=base["Normal"],
            fontSize=9, textColor=colors.HexColor("#8899bb"),
            alignment=TA_CENTER, spaceAfter=8),

        "section": ParagraphStyle("Sec", parent=base["Normal"],
            fontSize=11, textColor=BLUE, fontName="Helvetica-Bold",
            spaceBefore=14, spaceAfter=4,
            borderPad=0),

        "body": ParagraphStyle("Body", parent=base["Normal"],
            fontSize=9.5, textColor=TEXT_DARK, leading=15,
            alignment=TA_JUSTIFY),

        "code": ParagraphStyle("Code", parent=base["Code"],
            fontSize=7.5, backColor=LIGHT_BG, borderPad=8,
            leading=12, fontName="Courier"),

        "footer": ParagraphStyle("Footer", parent=base["Normal"],
            fontSize=7.5, textColor=colors.grey, alignment=TA_CENTER),
    }

    story = []

    # ── Banner ─────────────────────────────────────────────────────────────────
    story.append(Paragraph("📊  Financial Analytics Report", S["title"]))
    story.append(Spacer(1, 0.2*cm))
    story.append(Paragraph(
        f"Generated by NL-to-SQL Multi-Agent System  ·  "
        f"{datetime.now().strftime('%d %B %Y, %H:%M')}",
        S["subtitle"]
    ))
    story.append(HRFlowable(width="100%", thickness=2, color=BLUE, spaceAfter=10))

    # ── Question ───────────────────────────────────────────────────────────────
    story.append(Paragraph("Question", S["section"]))
    story.append(Paragraph(question, S["body"]))

    # ── SQL ────────────────────────────────────────────────────────────────────
    story.append(Paragraph("Generated SQL  (Data Analyst Agent)", S["section"]))
    safe_sql = sql.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;")
    story.append(Paragraph(safe_sql, S["code"]))

    # ── Data Summary ───────────────────────────────────────────────────────────
    story.append(Paragraph("Data Summary", S["section"]))
    story.append(Paragraph(summary, S["body"]))

    # ── Chart ──────────────────────────────────────────────────────────────────
    if fig is not None:
        story.append(Paragraph("Visualisation  (Reporting Agent)", S["section"]))
        img = _fig_to_image(fig)
        if img:
            story.append(img)

    # ── Narrative ──────────────────────────────────────────────────────────────
    story.append(Paragraph("Analytical Report  (Reporting Agent)", S["section"]))
    for para in narrative.split("\n\n"):
        para = para.strip()
        if para:
            story.append(Paragraph(para, S["body"]))
            story.append(Spacer(1, 0.2*cm))

    # ── Data Table ─────────────────────────────────────────────────────────────
    if not df.empty:
        story.append(Paragraph(
            f"Query Results  — {len(df):,} rows total (showing first 30)", S["section"]
        ))
        story.append(Spacer(1, 0.15*cm))
        story.append(_table_flowable(df))

    # ── Footer ─────────────────────────────────────────────────────────────────
    story.append(Spacer(1, 0.5*cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=MID_GREY))
    story.append(Paragraph(
        "Confidential  ·  Auto-generated by NL-to-SQL Multi-Agent System  ·  Do not distribute",
        S["footer"]
    ))

    doc.build(story)
    return buf.getvalue()
